#ifndef __WM_I2C_H__
#define __WM_I2C_H__

#include "driver/i2c.h"
#include "driver/gpio.h"

#ifdef __cplusplus
extern "C" {
#endif

enum
{
    REG_CHIP_CONTROL_1 = 0x0,
    REG_CHIP_CONTROL_2,
    REG_CHIP_PWR_MANAGEMENT,
    REG_ADC_PWR_MANAGEMENT,
    REG_DAC_PWR_MANAGEMENT,
    REG_CHIP_LOW_POWER_1,
    REG_CHIP_LOW_POWER_2,
    REG_ANALOG_VOLT_MANAGEMENT,
    REG_MASTER_MODE_CONTROL,
    REG_ADC_CONTROL_1,
    REG_ADC_CONTROL_2,
    REG_ADC_CONTROL_3,
    REG_ADC_CONTROL_4,
    REG_ADC_CONTROL_5,
    REG_ADC_CONTROL_6,
    REG_ADC_CONTROL_7,
    REG_ADC_CONTROL_8,
    REG_ADC_CONTROL_9,
    REG_ADC_CONTROL_10,
    REG_ADC_CONTROL_11,
    REG_ADC_CONTROL_12,
    REG_ADC_CONTROL_13,
    REG_ADC_CONTROL_14,
    REG_DAC_CONTROL_1,
    REG_DAC_CONTROL_2,
    REG_DAC_CONTROL_3,
    REG_DAC_CONTROL_4,
    REG_DAC_CONTROL_5,
    REG_DAC_CONTROL_6,
    REG_DAC_CONTROL_7,
    REG_DAC_CONTROL_8,
    REG_DAC_CONTROL_9,
    REG_DAC_CONTROL_10,
    REG_DAC_CONTROL_11,
    REG_DAC_CONTROL_12,
    REG_DAC_CONTROL_13,
    REG_DAC_CONTROL_14,
    REG_DAC_CONTROL_15,
    REG_DAC_CONTROL_16,
    REG_DAC_CONTROL_17,
    REG_DAC_CONTROL_18,
    REG_DAC_CONTROL_19,
    REG_DAC_CONTROL_20,
    REG_DAC_CONTROL_21,
    REG_DAC_CONTROL_22,
    REG_DAC_CONTROL_23,
    REG_DAC_CONTROL_24,
    REG_DAC_CONTROL_25,
    REG_DAC_CONTROL_26,
    REG_DAC_CONTROL_27,
    REG_DAC_CONTROL_28,
    REG_DAC_CONTROL_29,
    REG_DAC_CONTROL_30,
};

void es_i2c_init();

#ifdef __cplusplus
}
#endif

#endif // __WM_I2C_H__
